/**
 * generate-document — Edge Function
 * Accepts a POST with { template_id, brewery_data }, verifies the caller is an
 * active Full Suite subscriber, builds a .docx Word document using the docx npm
 * package, and returns it as a base64 string with a suggested filename.
 *
 * Deploy with:
 *   supabase functions deploy generate-document --no-verify-jwt
 *
 * The --no-verify-jwt flag is required because we perform our own JWT verification
 * inside the function (needed to access the Authorization header manually).
 */

import { createClient } from 'https://esm.sh/@supabase/supabase-js@2'
import {
  Document, Packer, Paragraph, TextRun, Table, TableRow, TableCell,
  HeadingLevel, AlignmentType, BorderStyle, WidthType, ShadingType,
  Footer, PageNumber,
} from 'npm:docx@8.5.0'

// ── CORS headers required for browser-to-edge-function calls ─────────────────

const CORS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Headers': 'authorization, x-client-info, apikey, content-type',
}

// ── Brand colours (no leading #) ──────────────────────────────────────────────

const NAVY  = '1A2744'
const AMBER = 'C8871A'
const WHITE = 'FFFFFF'
const GRAY  = '6B7280'
const LIGHT = 'F9FAFB'

// ── Template name lookup ──────────────────────────────────────────────────────

const TEMPLATE_NAMES: Record<string, string> = {
  legislator_meeting_request: 'Legislator Meeting Request Letter',
  brewery_tour_invitation:    'Brewery Tour Invitation',
  economic_impact_one_pager:  'Economic Impact One-Pager',
  written_testimony:          'Written Committee Testimony',
  customer_action_alert:      'Customer Action Alert Email',
}

// ═════════════════════════════════════════════════════════════════════════════
// DOCUMENT HELPERS
// ═════════════════════════════════════════════════════════════════════════════

/** Returns a blank paragraph — used as vertical spacing between sections. */
function spacer(): Paragraph {
  return new Paragraph({ children: [], spacing: { after: 0, before: 0, line: 240 } })
}

/** Returns a paragraph containing a single TextRun. Accepts optional styling. */
function p(
  text: string,
  opts: {
    bold?: boolean; italic?: boolean; size?: number; color?: string;
    align?: AlignmentType; spaceBefore?: number; spaceAfter?: number;
    font?: string;
  } = {}
): Paragraph {
  return new Paragraph({
    alignment: opts.align ?? AlignmentType.LEFT,
    spacing: {
      before: opts.spaceBefore ?? 0,
      after:  opts.spaceAfter  ?? 120,
    },
    children: [
      new TextRun({
        text,
        bold:    opts.bold   ?? false,
        italics: opts.italic ?? false,
        size:    (opts.size ?? 11) * 2,   // docx uses half-points
        color:   opts.color ?? '000000',
        font:    opts.font  ?? 'Calibri',
      }),
    ],
  })
}

/** Returns a styled heading paragraph (no built-in heading styles — manual styling). */
function heading(text: string, sizePt = 14, color = NAVY, spaceAfter = 160): Paragraph {
  return new Paragraph({
    spacing: { before: 200, after: spaceAfter },
    children: [
      new TextRun({ text, bold: true, size: sizePt * 2, color, font: 'Calibri' }),
    ],
  })
}

/** Returns a paragraph with a top border — used as a visual section divider. */
function rule(): Paragraph {
  return new Paragraph({
    border: { top: { style: BorderStyle.SINGLE, size: 6, color: AMBER } },
    spacing: { before: 160, after: 160 },
    children: [],
  })
}

/**
 * Builds the letterhead header block that appears at the top of every letter template:
 * the brewery name in large navy bold, followed by city/state and optional date.
 */
function letterhead(breweryName: string, cityState: string, date?: string): Paragraph[] {
  const blocks: Paragraph[] = [
    new Paragraph({
      spacing: { before: 0, after: 80 },
      children: [
        new TextRun({ text: breweryName.toUpperCase(), bold: true, size: 32, color: NAVY, font: 'Calibri' }),
      ],
    }),
    p(cityState, { color: GRAY, size: 11 }),
  ]
  if (date) {
    blocks.push(spacer())
    blocks.push(p(date, { size: 11 }))
  }
  return blocks
}

/** Builds the standard document footer with brand attribution and page numbers. */
function docFooter(): Footer {
  return new Footer({
    children: [
      new Paragraph({
        alignment: AlignmentType.CENTER,
        children: [
          new TextRun({
            text: 'Generated by The Craft Beer Brief | thecraftbeerbrief.com    Page ',
            size: 18,
            color: GRAY,
            font: 'Calibri',
          }),
          new TextRun({ children: [PageNumber.CURRENT], size: 18, font: 'Calibri' }),
          new TextRun({ text: ' of ', size: 18, color: GRAY, font: 'Calibri' }),
          new TextRun({ children: [PageNumber.TOTAL_PAGES], size: 18, font: 'Calibri' }),
        ],
      }),
    ],
  })
}

/** Wraps a list of content paragraphs in a Document with US Letter size, 1-inch margins. */
function wrapDocument(children: Paragraph[]): Document {
  return new Document({
    sections: [{
      properties: {
        page: {
          margin: { top: 1440, right: 1440, bottom: 1440, left: 1440 },
          size:   { width: 12240, height: 15840 },
        },
      },
      footers: { default: docFooter() },
      children,
    }],
  })
}

// ═════════════════════════════════════════════════════════════════════════════
// TEMPLATE 1 — LEGISLATOR MEETING REQUEST LETTER
// ═════════════════════════════════════════════════════════════════════════════

function buildLegislatorMeetingRequest(d: Record<string, string>): Document {
  const cityState = `${d.brewery_city}, ${d.brewery_state}`

  const children: Paragraph[] = [
    ...letterhead(d.brewery_name, cityState, d.date),
    spacer(),
    p(`${d.legislator_title} ${d.legislator_name}`),
    p(`${d.legislator_district} District, ${d.brewery_state} State Legislature`),
    spacer(),
    p(`Dear ${d.legislator_title} ${d.legislator_name}:`),
    spacer(),
    p(
      `I am writing on behalf of ${d.brewery_name}, a craft brewery located in ${cityState}, ` +
      `to respectfully request a brief meeting to discuss ${d.key_issue} and its impact on ` +
      `our brewery and the broader craft beer industry in ${d.brewery_state}.`
    ),
    spacer(),
    p(
      `${d.brewery_name} is proud to be part of ${d.brewery_city}'s small business community. ` +
      `We employ ${d.brewery_employees} local residents and contribute approximately ` +
      `${d.brewery_annual_revenue} annually to the local economy through wages, local purchasing, ` +
      `and tax revenue. Like many small craft breweries, we are deeply affected by state-level ` +
      `regulations that govern how we operate, sell, and grow our business.`
    ),
    spacer(),
    p(
      `We believe that ${d.key_issue} deserves thoughtful attention from state leadership. ` +
      `A conversation with your office would allow us to share our perspective, answer any ` +
      `questions you may have, and hear your thoughts on how to best support small manufacturers ` +
      `like us in ${d.brewery_state}.`
    ),
    spacer(),
    p(
      `We would be honored to welcome you to ${d.brewery_name} for a complimentary tour of our ` +
      `brewing facility at your convenience. Seeing a working craft brewery firsthand often ` +
      `provides valuable context for the policy discussions that affect our industry.`
    ),
    spacer(),
    p(
      `A meeting of 20–30 minutes would be greatly appreciated and can take place at your office, ` +
      `by phone, or here at our brewery. I can be reached at your convenience and am happy to ` +
      `work around your schedule. Thank you for your time and your service to ${d.legislator_district} District.`
    ),
    spacer(),
    p('Respectfully,'),
    spacer(),
    p(d.brewer_name, { bold: true }),
    p(d.brewer_title),
    p(d.brewery_name),
    p(cityState),
  ]

  return wrapDocument(children)
}

// ═════════════════════════════════════════════════════════════════════════════
// TEMPLATE 2 — BREWERY TOUR INVITATION
// ═════════════════════════════════════════════════════════════════════════════

function buildBreweryTourInvitation(d: Record<string, string>): Document {
  const cityState  = `${d.brewery_city}, ${d.brewery_state}`
  const today      = new Date().toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })

  // Split talking points by newline so they can be rendered as separate bullet lines
  const talkingPoints = (d.key_talking_points ?? '')
    .split('\n')
    .map(s => s.trim())
    .filter(Boolean)

  const children: Paragraph[] = [
    ...letterhead(d.brewery_name, `${d.brewery_address} · ${cityState}`, today),
    spacer(),
    p(`${d.official_title} ${d.official_name}`),
    spacer(),
    p(`Dear ${d.official_title} ${d.official_name}:`),
    spacer(),
    p(
      `On behalf of ${d.brewery_name}, founded in ${d.brewery_founded_year} right here in ` +
      `${d.brewery_city}, I would like to personally invite you for a tour of our brewery. ` +
      `We believe that building relationships between local businesses and elected officials ` +
      `strengthens our community, and we would be delighted to welcome you as our guest.`
    ),
    spacer(),
    p(
      `${d.brewery_name} employs ${d.brewery_employees} local residents and produces ` +
      `${d.annual_barrels} barrels of craft beer annually. We purchase ingredients and ` +
      `supplies from local vendors wherever possible, and we host community events throughout ` +
      `the year. Simply put, the health of ${d.brewery_city}'s small business ecosystem matters deeply to us.`
    ),
    spacer(),
    p(
      `During your visit, you would have the opportunity to see our brewing operations from ` +
      `grain to glass, meet our team, and sample some of our handcrafted beers. We would ` +
      `also welcome the chance to discuss several topics important to our industry, including:`
    ),
  ]

  // Render each talking point as an indented line
  for (const point of talkingPoints) {
    children.push(new Paragraph({
      spacing: { before: 80, after: 80 },
      indent: { left: 720 },
      children: [new TextRun({ text: `• ${point}`, size: 22, font: 'Calibri' })],
    }))
  }

  children.push(
    spacer(),
    p(
      `We are available on ${d.proposed_dates}. Please let us know what works best for ` +
      `your schedule and we will plan a tour tailored to your interests. A typical visit ` +
      `runs approximately 60–90 minutes, though we are happy to accommodate your availability.`
    ),
    spacer(),
    p(`We look forward to welcoming you to ${d.brewery_name}.`),
    spacer(),
    p('Warmly,'),
    spacer(),
    p(d.brewer_name, { bold: true }),
    p(`Owner/Brewer`),
    p(d.brewery_name),
    p(cityState),
  )

  return wrapDocument(children)
}

// ═════════════════════════════════════════════════════════════════════════════
// TEMPLATE 3 — ECONOMIC IMPACT ONE-PAGER
// ═════════════════════════════════════════════════════════════════════════════

/** Helper: build a two-column stat table row with a navy label cell and content cell. */
function statRow(label: string, value: string): TableRow {
  return new TableRow({
    children: [
      new TableCell({
        width: { size: 40, type: WidthType.PERCENTAGE },
        shading: { type: ShadingType.SOLID, fill: NAVY },
        borders: {
          top:    { style: BorderStyle.SINGLE, size: 1, color: NAVY },
          bottom: { style: BorderStyle.SINGLE, size: 1, color: NAVY },
          left:   { style: BorderStyle.SINGLE, size: 1, color: NAVY },
          right:  { style: BorderStyle.SINGLE, size: 1, color: NAVY },
        },
        children: [new Paragraph({
          spacing: { before: 80, after: 80 },
          children: [new TextRun({ text: label, bold: true, size: 20, color: WHITE, font: 'Calibri' })],
        })],
      }),
      new TableCell({
        width: { size: 60, type: WidthType.PERCENTAGE },
        shading: { type: ShadingType.SOLID, fill: LIGHT },
        borders: {
          top:    { style: BorderStyle.SINGLE, size: 1, color: NAVY },
          bottom: { style: BorderStyle.SINGLE, size: 1, color: NAVY },
          left:   { style: BorderStyle.SINGLE, size: 1, color: NAVY },
          right:  { style: BorderStyle.SINGLE, size: 1, color: NAVY },
        },
        children: [new Paragraph({
          spacing: { before: 80, after: 80 },
          children: [new TextRun({ text: value, bold: true, size: 22, color: NAVY, font: 'Calibri' })],
        })],
      }),
    ],
  })
}

function buildEconomicImpactOnePager(d: Record<string, string>): Document {
  const cityState    = `${d.brewery_city}, ${d.brewery_state}`
  const totalEmp     = (parseInt(d.full_time_employees, 10) || 0) + (parseInt(d.part_time_employees, 10) || 0)

  const econTable = new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      statRow('Full-Time Employees',      d.full_time_employees),
      statRow('Part-Time Employees',      d.part_time_employees),
      statRow('Total Annual Payroll',     d.annual_payroll),
      statRow('Annual Revenue',           d.annual_revenue),
      statRow('Annual Local Purchasing',  d.annual_local_purchases),
      statRow('Annual Visitors',          d.annual_visitors),
      statRow('Tax Contributions',        d.tax_contributions),
    ],
  })

  const communityTable = new Table({
    width: { size: 100, type: WidthType.PERCENTAGE },
    rows: [
      statRow('Community Events Per Year',      d.community_events_per_year),
      statRow('Annual Charitable Contributions', d.charity_donations_annual),
    ],
  })

  const children: Paragraph[] = [
    // Title block
    new Paragraph({
      spacing: { before: 0, after: 80 },
      children: [new TextRun({ text: d.brewery_name.toUpperCase(), bold: true, size: 36, color: NAVY, font: 'Calibri' })],
    }),
    new Paragraph({
      spacing: { before: 0, after: 80 },
      children: [new TextRun({ text: `Economic Impact Summary | ${cityState} | Est. ${d.brewery_founded_year}`, size: 22, color: AMBER, font: 'Calibri', bold: true })],
    }),
    // Summary bar
    new Paragraph({
      spacing: { before: 80, after: 160 },
      children: [
        new TextRun({ text: `${totalEmp} Employees  ·  `, bold: true, size: 22, color: NAVY, font: 'Calibri' }),
        new TextRun({ text: `${d.annual_revenue} Revenue  ·  `, bold: true, size: 22, color: NAVY, font: 'Calibri' }),
        new TextRun({ text: `${d.annual_visitors} Annual Visitors`, bold: true, size: 22, color: NAVY, font: 'Calibri' }),
      ],
    }),
    rule(),
    heading('Economic Impact', 13),
    econTable,
    spacer(),
    heading('Community Contribution', 13),
    communityTable,
    spacer(),
    // Narrative
    p(
      `${d.brewery_name} has been a cornerstone of the ${d.brewery_city} community since ${d.brewery_founded_year}. ` +
      `We employ ${totalEmp} local residents, support other local businesses through our purchasing, ` +
      `and welcome thousands of visitors to our taproom each year. Our commitment to the community ` +
      `goes beyond beer — we host ${d.community_events_per_year} community events annually and contribute ` +
      `${d.charity_donations_annual} to local charitable causes.`,
      { size: 10, spaceAfter: 200 }
    ),
    rule(),
    heading('Our Policy Ask', 13, AMBER),
    p(d.key_policy_ask, { spaceAfter: 200 }),
  ]

  return wrapDocument(children)
}

// ═════════════════════════════════════════════════════════════════════════════
// TEMPLATE 4 — WRITTEN COMMITTEE TESTIMONY
// ═════════════════════════════════════════════════════════════════════════════

function buildWrittenTestimony(d: Record<string, string>): Document {
  const cityState = `${d.brewery_city}, ${d.brewery_state}`
  const posLabel  = d.position?.toUpperCase() ?? 'SUPPORT'

  // Format the position verb for narrative use
  const posVerb =
    d.position === 'Oppose' ? 'in opposition to' :
    d.position === 'Amend'  ? 'seeking amendment to' :
    'in support of'

  const children: Paragraph[] = [
    heading('WRITTEN TESTIMONY', 16),
    rule(),
    p(`Submitted to: ${d.committee_name}`, { bold: true }),
    p(`Re: ${d.bill_number} — ${d.bill_title}`),
    p(`Hearing Date: ${d.hearing_date}`),
    p(`Submitted by: ${d.brewer_name}, ${d.brewer_title}`),
    p(`Organization: ${d.brewery_name}, ${cityState}`),
    rule(),
    // Position statement
    new Paragraph({
      spacing: { before: 160, after: 160 },
      children: [
        new TextRun({ text: 'POSITION:  ', bold: true, size: 26, color: NAVY, font: 'Calibri' }),
        new TextRun({ text: `${posLabel} ${d.bill_number}`, bold: true, size: 26, color: posLabel === 'OPPOSE' ? 'DC2626' : posLabel === 'AMEND' ? AMBER : '16A34A', font: 'Calibri' }),
      ],
    }),
    rule(),
    heading('INTRODUCTION', 12),
    p(
      `${d.brewery_name} respectfully submits this written testimony ${posVerb} ${d.bill_number}, ` +
      `${d.bill_title}. ${d.brewery_name} is a craft brewery located in ${cityState}, employing ` +
      `local residents and contributing to the economic vitality of our community. As a small ` +
      `manufacturer directly affected by beer-related legislation, we have a significant stake ` +
      `in the outcome of this legislation.`
    ),
    spacer(),
    // Arguments
    heading(`ARGUMENT 1`, 12, AMBER),
    p(d.key_argument_1 ?? ''),
    spacer(),
    heading(`ARGUMENT 2`, 12, AMBER),
    p(d.key_argument_2 ?? ''),
    spacer(),
    heading(`ARGUMENT 3`, 12, AMBER),
    p(d.key_argument_3 ?? ''),
    rule(),
    heading(`IMPACT ON ${d.brewery_name.toUpperCase()}`, 12),
    p('Financial Impact:', { bold: true, spaceAfter: 60 }),
    p(d.financial_impact ?? '', { spaceAfter: 160 }),
    p('Employee Impact:', { bold: true, spaceAfter: 60 }),
    p(d.employee_impact ?? '', { spaceAfter: 160 }),
    p('Community Impact:', { bold: true, spaceAfter: 60 }),
    p(d.community_impact ?? '', { spaceAfter: 200 }),
    rule(),
    heading('REQUESTED ACTION', 12),
    p(d.requested_action ?? ''),
    spacer(),
    spacer(),
    p('Respectfully submitted,'),
    spacer(),
    p(d.brewer_name, { bold: true }),
    p(d.brewer_title),
    p(d.brewery_name),
    p(cityState),
  ]

  return wrapDocument(children)
}

// ═════════════════════════════════════════════════════════════════════════════
// TEMPLATE 5 — CUSTOMER ACTION ALERT EMAIL
// ═════════════════════════════════════════════════════════════════════════════

function buildCustomerActionAlert(d: Record<string, string>): Document {
  const actionLines = (d.action_requested ?? '')
    .split('\n').map(s => s.trim()).filter(Boolean)

  const children: Paragraph[] = [
    // Subject line suggestion
    new Paragraph({
      spacing: { before: 0, after: 80 },
      border: {
        bottom: { style: BorderStyle.SINGLE, size: 4, color: AMBER },
      },
      children: [
        new TextRun({ text: 'SUGGESTED SUBJECT LINE:  ', bold: true, size: 20, color: GRAY, font: 'Calibri' }),
        new TextRun({
          text: `Action Needed: ${d.issue_title} Could Affect ${d.brewery_name}`,
          bold: true, size: 22, color: NAVY, font: 'Calibri',
        }),
      ],
    }),
    spacer(),
    heading('EMAIL BODY', 12, GRAY),
    spacer(),
    p(`Dear ${d.brewery_name} Community,`),
    spacer(),
    p(d.issue_summary ?? ''),
    spacer(),
    heading('What This Means For You', 12),
    p(d.what_it_means_for_customers ?? ''),
    spacer(),
    heading('What You Can Do', 12),
  ]

  if (actionLines.length > 0) {
    actionLines.forEach((line, i) => {
      children.push(new Paragraph({
        spacing: { before: 80, after: 80 },
        indent: { left: 720 },
        children: [new TextRun({ text: `${i + 1}. ${line}`, size: 22, font: 'Calibri' })],
      }))
    })
  } else {
    children.push(p(d.action_requested ?? ''))
  }

  children.push(
    spacer(),
    // Contact info box
    new Paragraph({
      spacing: { before: 160, after: 160 },
      border: {
        top:    { style: BorderStyle.SINGLE, size: 4, color: NAVY },
        bottom: { style: BorderStyle.SINGLE, size: 4, color: NAVY },
        left:   { style: BorderStyle.THICK,  size: 12, color: AMBER },
        right:  { style: BorderStyle.SINGLE, size: 4, color: NAVY },
      },
      indent: { left: 360 },
      children: [
        new TextRun({ text: 'Legislator Contact Information:  ', bold: true, size: 22, color: NAVY, font: 'Calibri' }),
        new TextRun({ text: d.legislator_contact_info ?? '', size: 22, font: 'Calibri' }),
      ],
    }),
    p(`Act by: ${d.deadline_date ?? 'As soon as possible'}`, { bold: true, color: 'DC2626', size: 12 }),
    spacer(),
    p(
      `Together, we can make a difference for ${d.brewery_name} and for craft beer across our state. ` +
      `Thank you for your support — it means everything to us.`
    ),
    spacer(),
    p('Cheers,'),
    spacer(),
    p(d.brewer_name, { bold: true }),
    p(d.brewery_name),
    d.brewery_website ? p(d.brewery_website, { color: AMBER }) : spacer(),
  )

  return wrapDocument(children)
}

// ═════════════════════════════════════════════════════════════════════════════
// ROUTER — dispatches to the correct template builder
// ═════════════════════════════════════════════════════════════════════════════

function generateDocument(templateId: string, data: Record<string, string>): Document {
  switch (templateId) {
    case 'legislator_meeting_request': return buildLegislatorMeetingRequest(data)
    case 'brewery_tour_invitation':    return buildBreweryTourInvitation(data)
    case 'economic_impact_one_pager':  return buildEconomicImpactOnePager(data)
    case 'written_testimony':          return buildWrittenTestimony(data)
    case 'customer_action_alert':      return buildCustomerActionAlert(data)
    default: throw new Error(`Unknown template_id: ${templateId}`)
  }
}

// ═════════════════════════════════════════════════════════════════════════════
// MAIN HANDLER
// ═════════════════════════════════════════════════════════════════════════════

Deno.serve(async (req: Request) => {
  // Return CORS pre-flight immediately without processing
  if (req.method === 'OPTIONS') {
    return new Response(null, { headers: CORS })
  }

  const json = (body: object, status = 200) =>
    new Response(JSON.stringify(body), {
      status,
      headers: { ...CORS, 'Content-Type': 'application/json' },
    })

  try {
    // ── 1. JWT verification ──────────────────────────────────────────────────
    const authHeader = req.headers.get('Authorization') ?? ''
    if (!authHeader.startsWith('Bearer ')) {
      return json({ error: 'Missing authorization header' }, 401)
    }

    const supabase = createClient(
      Deno.env.get('SUPABASE_URL')              ?? '',
      Deno.env.get('SUPABASE_SERVICE_ROLE_KEY') ?? ''
    )

    const token = authHeader.slice(7)
    const { data: { user }, error: authError } = await supabase.auth.getUser(token)
    if (authError || !user) {
      return json({ error: 'Unauthorized — invalid token' }, 401)
    }

    // ── 2. Full Suite subscription check ────────────────────────────────────
    const { data: profile, error: profileError } = await supabase
      .from('users')
      .select('subscription_tier, subscription_status, brewery_id')
      .eq('id', user.id)
      .single()

    if (profileError || !profile) {
      return json({ error: 'Could not load user profile' }, 500)
    }

    if (profile.subscription_tier !== 'full_suite' || profile.subscription_status !== 'active') {
      return json({ error: 'Full Suite subscription required to generate documents' }, 403)
    }

    // ── 3. Parse request body ────────────────────────────────────────────────
    const body = await req.json()
    const { template_id, brewery_data } = body as {
      template_id:   string
      brewery_data:  Record<string, string>
    }

    if (!template_id || !brewery_data) {
      return json({ error: 'Missing template_id or brewery_data' }, 400)
    }

    if (!TEMPLATE_NAMES[template_id]) {
      return json({ error: `Unknown template: ${template_id}` }, 400)
    }

    // ── 4. Generate the Word document ────────────────────────────────────────
    const doc    = generateDocument(template_id, brewery_data)
    const buffer = await Packer.toBuffer(doc)

    // Convert ArrayBuffer → base64 in chunks to avoid call-stack overflow
    const bytes  = new Uint8Array(buffer)
    let binary   = ''
    const CHUNK  = 8192
    for (let i = 0; i < bytes.length; i += CHUNK) {
      binary += String.fromCharCode(...bytes.subarray(i, i + CHUNK))
    }
    const base64   = btoa(binary)
    const filename = `${template_id.replace(/_/g, '-')}-${new Date().toISOString().slice(0, 10)}.docx`

    // ── 5. Log the generation (fire-and-forget; don't fail the request if it errors) ──
    supabase.from('playbook_generations').insert({
      brewery_id:    profile.brewery_id,
      template_id,
      template_name: TEMPLATE_NAMES[template_id],
      brewery_data,
    }).then(() => {}).catch(() => {})

    // ── 6. Return encoded document ───────────────────────────────────────────
    return json({ base64, filename })

  } catch (err: unknown) {
    const msg = err instanceof Error ? err.message : String(err)
    console.error('[generate-document] Error:', msg)
    return json({ error: 'Document generation failed', detail: msg }, 500)
  }
})
